title: <p align="center"> Neelima Guntupalli </p>

logo: "/images/profile_pic.JPG?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/neelimag/">LinkedIn</a> |
  <a href="https://github.com/neel-machine">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in ML/AI at Liverpool John moores University.
  <br><br>
  I am currently looking for internships.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
